version: 2.0.{build}
image: Visual Studio 2017
before_build:
 - dotnet restore
build_script:
 - dotnet build /verbosity:quiet "TempMail-API.sln"
test_script:
 - dotnet test --no-build .\test\TempMail.Tests\TempMail.Tests.csproj
